geoblacklight:
  image: geoblacklight/geoblacklight
  environment:
    RAILS_ENV: development
    SOLR_URL: http://solr:8983/solr/geoblacklight
    GEOBLACKLIGHT_DATABASE_USER: postgres
    GEOBLACKLIGHT_DATABASE_PASSWORD: postgres
  volumes:
    - ./geoblacklight/database.yml:/usr/src/geoblacklight/config/database.yml
    - ./geoblacklight/start.sh:/usr/src/geoblacklight/start.sh
  links:
    - solr
    - geoserver
    - db

solr:
  image: geoblacklight/solr
  volumes:
    - ../../data/solr_documents:/opt/solr-5.2.1/solr_documents
    - ./solr/start.sh:/opt/solr-5.2.1/start.sh

geoserver:
  image: geoblacklight/geoserver
  volumes:
    - ./geoserver:/usr/local/tomcat/webapps/geoserver/data
    - ../../data:/data
  links:
    - db

db:
  image: geoblacklight/postgres
  volumes:
    - ./postgres/initdb-postgis.sh:/docker-entrypoint-initdb.d/postgis.sh
    - ../../data/shapefiles:/root/shapefiles
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres

loris:
  image: lorisimageserver/loris
  volumes:
    - ../../data/images:/usr/local/share/images

nginx:
  image: nginx
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  links:
    - geoblacklight
    - solr
    - geoserver
    - db
    - loris
  ports:
    - "80:80"